all:hw3_1.cpp hw3_2.cpp hw3_3.cpp
	g++ hw3_1.cpp -o hw3_1
	g++ hw3_2.cpp -o hw3_2
	g++ hw3_3.cpp -o hw3_3
clean:
	rm -f hw3_1 hw3_2 hw3_3
1:hw3_1 1.txt os_hw3.sh
	./hw3_1 < 1.txt | ./os_hw3.sh
2:hw3_2 2.txt os_hw3.sh
	./hw3_2 < 2.txt | ./os_hw3.sh
3:hw3_3 3.txt os_hw3.sh
	./hw3_3 < 3.txt | ./os_hw3.sh
